[package]
name = "abstractions"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
nix = { version = "0.29.0", features = ["fs", "term", "process", "signal", "poll", "ioctl", "time", "event"] }
log = {version = "0.4.22"}
