[plugins.signal]
enable = true
path = "target/debug/libsignal.so"
system = true
order = 2

[plugins.logger]
enable = true
path = "target/debug/liblogfile.so"
system = true
order = 100

[plugins.poll]
enable = true
path = "target/debug/libpoll.so"
system = true
order = 1

[plugins.config_watcher]
path = "target/debug/libconfig_watcher.so"
enable = true
order = 10  # Порядок загрузки (после основных плагинов)
